import type { WgClientConfig, WgServerKeys, WgNetworkConfig } from "@/types";

export function generateMikrotikClientRsc(
  client: WgClientConfig,
  serverKeys: WgServerKeys,
  network: WgNetworkConfig
): string {
  const lines: string[] = [];
  const [endpointAddr, endpointPort] = client.endpoint.split(":");

  lines.push(`# MikroTik WireGuard Client Configuration`);
  lines.push(`# Client: ${client.name} (${client.ip})`);
  lines.push(`# Generated by MikroTik VPN Manager`);
  lines.push(``);

  // Create WireGuard interface on client MikroTik
  lines.push(`# --- Create WireGuard Interface ---`);
  lines.push(
    `/interface/wireguard/add name=wireguard-client private-key="${client.keys.privateKey}"`
  );
  lines.push(``);

  // Assign IP
  lines.push(`# --- Assign IP Address ---`);
  lines.push(
    `/ip/address/add address=${client.ip}/${network.subnetMask} interface=wireguard-client`
  );
  lines.push(``);

  // Add server as peer
  lines.push(`# --- Add Server Peer ---`);
  lines.push(
    `/interface/wireguard/peers/add interface=wireguard-client public-key="${serverKeys.publicKey}" preshared-key="${client.psk}" endpoint-address=${endpointAddr} endpoint-port=${endpointPort} allowed-address=${client.allowedIps} persistent-keepalive=${client.keepalive}`
  );

  return lines.join("\n");
}
