import type { WgServerConfig, WgClientConfig } from "@/types";

export function generatePeerRsc(
  server: WgServerConfig,
  clients: WgClientConfig[]
): string {
  const lines: string[] = [];

  lines.push(`# WireGuard Peers Only`);
  lines.push(`# Add these peers to an existing ${server.interfaceName} interface`);
  lines.push(`# Generated by MikroTik VPN Manager`);
  lines.push(``);

  for (const client of clients) {
    lines.push(
      `/interface/wireguard/peers/add interface=${server.interfaceName} public-key="${client.keys.publicKey}" preshared-key="${client.psk}" allowed-address=${client.ip}/32 comment="${client.name}"`
    );
  }

  return lines.join("\n");
}
