import type { WgServerConfig, WgNetworkConfig, WgServerKeys, WgClientConfig } from "@/types";

export function generateServerRsc(
  server: WgServerConfig,
  network: WgNetworkConfig,
  serverKeys: WgServerKeys,
  clients: WgClientConfig[]
): string {
  const lines: string[] = [];

  lines.push(`# WireGuard Server Configuration`);
  lines.push(`# Generated by MikroTik VPN Manager`);
  lines.push(`# Interface: ${server.interfaceName}`);
  lines.push(``);

  // Create WireGuard interface
  lines.push(`# --- Create WireGuard Interface ---`);
  lines.push(
    `/interface/wireguard/add name=${server.interfaceName} listen-port=${server.listenPort} private-key="${serverKeys.privateKey}"`
  );
  lines.push(``);

  // Assign IP address
  lines.push(`# --- Assign IP Address ---`);
  lines.push(
    `/ip/address/add address=${network.serverIp}/${network.subnetMask} interface=${server.interfaceName}`
  );
  lines.push(``);

  // Firewall rules
  lines.push(`# --- Firewall Rules ---`);
  lines.push(
    `/ip/firewall/filter/add chain=input action=accept protocol=udp dst-port=${server.listenPort} comment="Allow WireGuard"`
  );
  lines.push(
    `/ip/firewall/filter/add chain=forward action=accept in-interface=${server.interfaceName} comment="Allow WG Forward In"`
  );
  lines.push(
    `/ip/firewall/filter/add chain=forward action=accept out-interface=${server.interfaceName} comment="Allow WG Forward Out"`
  );
  lines.push(``);

  // NAT masquerade
  lines.push(`# --- NAT Masquerade ---`);
  lines.push(
    `/ip/firewall/nat/add chain=srcnat action=masquerade src-address=${network.subnet}/${network.subnetMask} comment="WG NAT"`
  );
  lines.push(``);

  // Peers
  lines.push(`# --- Peers ---`);
  for (const client of clients) {
    const allowedAddress = [
      `${client.ip}/32`,
      ...(client.lanSegments ?? []),
    ].join(",");
    lines.push(
      `/interface/wireguard/peers/add interface=${server.interfaceName} public-key="${client.keys.publicKey}" preshared-key="${client.psk}" allowed-address=${allowedAddress} comment="${client.name}"`
    );
  }

  // Static routes for LAN segments
  const clientsWithSegments = clients.filter(
    (c) => c.lanSegments && c.lanSegments.length > 0
  );
  if (clientsWithSegments.length > 0) {
    lines.push(``);
    lines.push(`# --- Static Routes for LAN Segments ---`);
    for (const client of clientsWithSegments) {
      for (const segment of client.lanSegments!) {
        lines.push(
          `/ip/route/add dst-address=${segment} gateway=${client.ip} comment="${client.name} LAN"`
        );
      }
    }
  }

  return lines.join("\n");
}
